### ISSUE TITLE
CSS Altered/removed

### ISSUE THREAD

**Issue by hellodaniel** [ankit/stylebot#168]
I've been trying to implement cross-browser CSS3 gradients and I've noticed that Stylebot automatically removes much of the code. This wouldn't be a problem if it kept the webkit code, but it doesn't seem to. 

e.g.: 

``` css
selector {
background-color: #b7d7cc;
background-image: -webkit-gradient(linear, left top, right bottom, from(rgb(183, 215, 204)), to(rgb(255, 255, 255)));
background-image: -webkit-linear-gradient(left top, rgb(183, 215, 204), rgb(255, 255, 255));
background-image: -moz-linear-gradient(left top, rgb(183, 215, 204), rgb(255, 255, 255));
background-image: -o-linear-gradient(left top, rgb(183, 215, 204), rgb(255, 255, 255));
background-image: -ms-linear-gradient(left top, rgb(183, 215, 204), rgb(255, 255, 255));
background-image: linear-gradient(left top, rgb(183, 215, 204), rgb(255, 255, 255));
filter: progid:DXImageTransform.Microsoft.gradient(GradientType=1,StartColorStr='#b7d7cc', EndColorStr='#ffffff');
}
```

becomes

``` css
selector {
    background-color: #b7d7cc;
    background-image: linear-gradient(left top, rgb(183, 215, 204), rgb(255, 255, 255));
    filter: progid:DXImageTransform.Microsoft.gradient(GradientType=1,StartColorStr='#b7d7cc', EndColorStr='#ffffff');
}
```

and, thus, doesn't work. 

Thanks.
