### ISSUE TITLE
Inserting unicode in content doesn't work

### ISSUE THREAD

**Issue by joakimc** [ankit/stylebot#385]
If this worked it would be possible to insert icons like this:

```css
.theElement {
  font-family: FontAwesone;
  content: "\ffed";
}
```

Instead it becomes:

```css
.theElement {
  font-family: FontAwesone;
  content: "";
}
```
