### ISSUE TITLE
CSS3 not() selector crashes page

### ISSUE THREAD

**Issue by creckord** [ankit/stylebot#418]
When entering custom CSS for a site, the tab crashes as soon as I enter the opening bracket to the `:not` selector. I can even enter the complete CSS rule block sans the `:not` selector first, it will still crash as soon as :not( is added.

Example: 
- Go to any IMDB page, e.g. http://www.imdb.com/title/tt3165612/
- Open StyleBot's Custom CSS editor
- Try to enter the following:

``` css
    div.article:not([id]) {
       background: green;
    }
```

I didn't check other CSS3, so maybe this is a general issue with CSS3 support?
