### ISSUE TITLE
@font-face injection stopped working due to "!important"

### ISSUE THREAD

**Issue by kojiishi** [ankit/stylebot#559]
I've been injecting:
```css
@font-face {
  font-family: 'MS PGothic';
  src: local('Meiryo');
}
```
to replace old fonts to more modern ones. This used to work, but stopped working recently. When I inspect the page:
```html
<style type="text/css" id="stylebot-css-zai.diamond.jp">@font-face {
  font-family: 'MS PGothic' !important;
  src: local('Meiryo') !important;
}
</style>
```
and this `!important` seems to be the cause. Is this a recent change? Is there a way to not to add this?
