### ISSUE TITLE
[Bug] Editor unscrollable

### ISSUE THREAD

**Issue by Higurashi-kagome** [ankit/stylebot#645]
### Describe the bug

When selected the text of the editor by the cursor, we can't scroll to the end of the editor.

### Browser

Chrome90、Win10

### To Reproduce
- Go to [GitHub](https://github.com/)
- Open the editor and input the text blow:
	

	<details>
	<summary>Details</summary>

	```CSS
	  @media screen and(min-width: 320px)and(max-width: 359px){
	  html{
	  font-size: 12.8px;
	  }
	  }
	  @media screen and(min-width: 360px)and(max-width: 374px){
	  html{
	  font-size: 14.4px;
	  }
	  }
	  @media screen and(min-width: 375px)and(max-width: 385px){
	  html{
	  font-size: 15px;
	  }
	  }
	  @media screen and(min-width: 386px)and(max-width: 392px) {
	  html {
	  font-size: 15.44px;
	  }
	  }
	  @media screen and(min-width: 393px)and(max-width: 400px){
	  html{
	  font-size: 16px;
	  }
	  }
	  @media screen and(min-width: 401px)and(max-width: 414px){
	  html{
	  font-size: 16.48px;
	  }
	  }
	  @media screen and(min-width: 750px)and(max-width: 799px){
	  html{
	  font-size: 30.72px;
	  }
	  }
	```

	</details>

- Try to select text from the second line to the end.
- Will find can't scroll to the bottom.

### Expected behavior

Should be scrollable when selected text.

### Screenshots

<details>
<summary>Details</summary>

![demo](https://user-images.githubusercontent.com/51501079/117762650-26a4c500-b25c-11eb-8293-a6b26aa2ae8e.gif)

</details>
