### ISSUE TITLE
[Bug] Webkit definition

### ISSUE THREAD

**Issue by code-fanatic** [ankit/stylebot#794]
### Describe the bug
The code below gives says `No definition found for '-webkit-box-shadow:'`
```css
.form-control:-webkit-autofill {
 -webkit-box-shadow: 0 0 0 25px black inset;
 -webkit-text-fill-color: #959fe9;
}
```

### Browser
`Chrome` 131.0.6778.205 (Official Build) (64-bit)
`Windows 11 Pro` 24H2

### To Reproduce
- Go to 'Any website'
- Open `Style bot Extension`
- Click `Open Stylebot` 
- Open `Code` tab
- Paste the CSS code given above

### Expected behavior
Stylebot should not suggest this definition because this code works fine in Chrome.

### Screenshots
Not applicable

### Additional context
Not applicable
